# This is a TOML document. Boom~
#host = "127.0.0.1"
#port = 3306
#user = "root"
#pswd = "root123456"
#dbname = "casbin"
#charset = "utf8mb4"

host = "123.206.120.144"
port = 3306
user = "root"
pswd = "W2+Wmikvb9XXu4X2n7w="
dbname = "casbin"
charset = "utf8mb4"